name: mal_clone
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #* Helper
  get: ^4.6.5
  logger: any
  url_launcher: ^6.1.9
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  flutter_sticky_header: ^0.6.5
  flutter_native_splash: ^2.2.18
  palette_generator: ^0.3.3+2
  video_player: ^2.5.3
  flutter_inappwebview: ^5.7.2+3
  expandable: ^5.0.1
  dart_code_metrics: ^5.6.0

  #* Platform Info
  package_info_plus: ^3.0.3
  device_info_plus: ^8.1.0
  network_info_plus: ^3.0.2
  connectivity_plus: ^3.0.3

  #* State Management
  get_it: ^7.2.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1

  #* Network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  retrofit: ">=3.0.0 <4.0.0"

  #* Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ">=4.0.0 <5.0.0"
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo/
